services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - monitoring-net
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - monitoring-net
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    network_mode: host
    pid: host
    volumes:
      - /:/host:ro,rslave
      - /sys:/sys:ro
      - /proc:/proc:ro
      - hvac-data:/var/lib/node_exporter/textfile_collector
    command:
      - --path.rootfs=/host
      - --collector.hwmon
      - --collector.textfile.directory=/var/lib/node_exporter/textfile_collector
    restart: unless-stopped

  smartctl_exporter:
    image: matusnovak/prometheus-smartctl:latest
    container_name: smartctl_exporter
    networks:
      - monitoring-net
    privileged: true
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    networks:
      - monitoring-net
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    restart: unless-stopped

  hvac_exporter:
    build:
      context: ./textfile_exporter
    container_name: hvac_exporter
    networks:
      - monitoring-net
    environment:
      HVAC_IP: ${HVAC_IP}
    volumes:
      - hvac-data:/data
    restart: unless-stopped

  apcupsd_exporter:
    build:
      context: ./apcupsd_exporter
    container_name: apcupsd_exporter
    ports:
      - "9162:9162"
    environment:
      APC_ADDRESS: ${APC_ADDRESS}
      TELEMETRY_ADDR: :9102
    restart: unless-stopped

volumes:
  grafana-data:
  prometheus-data:
  hvac-data:

networks:
  monitoring-net:
