global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['10.0.1.6:9100']

  - job_name: 'smartctl'
    static_configs:
      - targets: ['smartctl_exporter:9902']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus_exporter'
    static_configs:
      - targets: ['10.0.1.6:9101']
